[package]
name = "grandtheftmeta"
version = "0.1.2"
description = "FiveM vehicle handling.meta bulk editor"
authors = ["Yos"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "grandtheftmeta_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"          # recursive folder walking
regex = "1"            # surgical XML patching
quick-xml = "0.36"     # XML parsing for scan

[features]
# This feature is used for production builds or when a dev server is not specified.
custom-protocol = ["tauri/custom-protocol"]
